name: Ruby CI

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  test:
    strategy:
      fail-fast: true
      matrix:
        ruby: [2.4, 2.5, 2.6]
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
    # To automatically get bug fixes and new Ruby versions for ruby/setup-ruby,
    # change this to (see https://github.com/ruby/setup-ruby#versioning):
      uses: ruby/setup-ruby@v1
      # uses: ruby/setup-ruby@ec106b438a1ff6ff109590de34ddc62c540232e0
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Install minitest
      run: gem install minitest
    - name: Run tests
      run: ruby test/commitment_test.rb
